//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int PostId { get; set; }
        public string CommentText { get; set; }
        public string Email { get; set; }
        public string Url { get; set; }
        public string CommentedBy { get; set; }
        public Nullable<System.DateTime> CommentedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
